name: ナレッジ・ドメイン知識
description: ドメイン知識・ナレッジはこちら
title: '[ナレッジ]: '
labels: ["good first issue"]
body:
  - type: textarea
    id: content
    attributes:
      label: 概要
      description: ナレッジの概要を記載してください。
